Repository SynergyX-AI-Pattern/SynergyX-Server, pull requests merged in 2025-07, with the labels that each got.

#45 Feat/#44 div change amount
  src/main/java/com/synergyx/trading/config/KisProperties.java
  src/main/java/com/synergyx/trading/controller/KisTestController.java
  src/main/java/com/synergyx/trading/model/StockDetail.java
  src/main/java/com/synergyx/trading/service/kisService/KisDividendScheduleService.java
  src/main/java/com/synergyx/trading/service/kisService/KisOhlcvUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisPriceUpdateService.java
  src/main/java/com/synergyx/trading/service/stockService/detail/StockDetailQueryServiceImpl.java
  src/main/java/com/synergyx/trading/util/ParsingUtil.java
Labels: ✨ feature

#47 [REFACTOR] 백테스팅 스웨거 주석 수정 #5
  src/main/java/com/synergyx/trading/controller/BacktestController.java
Labels: ♻️ refactor

#48 [MOVE] 패턴 기간 enum 경로 이동 및 연관 수정 #3
  src/main/java/com/synergyx/trading/enums/PeriodUnit.java
  src/main/java/com/synergyx/trading/model/Pattern.java
  src/main/java/com/synergyx/trading/service/patternService/PatternCommandServiceImpl.java
Labels: ♻️ refactor

#51 Ci cd/#50 add firebase
  .github/workflows/dev_deploy.yml
  .gitignore
Labels: 🚀 ci

#52 [REFACTOR] firebase 경로 application.yml에서 읽어오도록 변경 #50
  src/main/java/com/synergyx/trading/config/FirebaseConfig.java
  src/main/java/com/synergyx/trading/model/Notification.java
Labels: 🚀 ci

#53 Feat/#46 kis ohlcv 3m 5y
  src/main/java/com/synergyx/trading/controller/KisTestController.java
  src/main/java/com/synergyx/trading/controller/StockController.java
  src/main/java/com/synergyx/trading/model/StockOhlcv1d.java
  src/main/java/com/synergyx/trading/model/StockOhlcv1h.java
  src/main/java/com/synergyx/trading/model/StockOhlcv1m.java
  src/main/java/com/synergyx/trading/repository/KisTokenRepository.java
  src/main/java/com/synergyx/trading/repository/StockOhlcv1dRepository.java
  src/main/java/com/synergyx/trading/repository/StockOhlcv1hRepository.java
  src/main/java/com/synergyx/trading/repository/StockOhlcv1mRepository.java
  src/main/java/com/synergyx/trading/repository/StockOhlcvRepository.java
  src/main/java/com/synergyx/trading/repository/StockRepository.java
  src/main/java/com/synergyx/trading/scheduler/KisStockScheduler.java
  src/main/java/com/synergyx/trading/service/kisService/Kis1dOhlcvUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/Kis1hOhlcvUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/Kis1mOhlcvUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisDividendScheduleService.java
  src/main/java/com/synergyx/trading/service/kisService/KisOhlcvUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisPriceUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisPsrUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisRoeUpdateService.java
  src/main/java/com/synergyx/trading/service/kisService/KisTokenServiceImpl.java
  src/main/java/com/synergyx/trading/util/KisOhlcvCompressor.java
  src/main/java/com/synergyx/trading/util/OhlcvCompareUtil.java
  src/main/resources/data/1m_sample_kis_response.json
Labels: ✨ feature

#58 [FEAT] 패턴 적용 시 진입 시점 및 진입 가격 저장 기능 추가 #57
  src/main/java/com/synergyx/trading/dto/patternApply/PatternApplyRequestDTO.java
  src/main/java/com/synergyx/trading/dto/patternApply/PatternApplyResponseDTO.java
  src/main/java/com/synergyx/trading/model/PatternApply.java
  src/main/java/com/synergyx/trading/repository/StockOhlcvRepository.java
  src/main/java/com/synergyx/trading/service/patternApplyService/PatternApplyServiceImpl.java
Labels: ✨ feature

#61 [FEAT] 패턴 적용 정보 수정, 해제 기능 구현 #60
  src/main/java/com/synergyx/trading/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/synergyx/trading/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/synergyx/trading/controller/PatternApplyController.java
  src/main/java/com/synergyx/trading/dto/patternApply/PatternApplyRequestDTO.java
  src/main/java/com/synergyx/trading/service/patternApplyService/PatternApplyService.java
  src/main/java/com/synergyx/trading/service/patternApplyService/PatternApplyServiceImpl.java
Labels: ✨ feature

#64 [FEAT] 최소 수익률 조건 필드 추가 #62
  src/main/java/com/synergyx/trading/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/synergyx/trading/dto/patternApply/PatternApplyRequestDTO.java
  src/main/java/com/synergyx/trading/dto/patternApply/PatternApplyResponseDTO.java
  src/main/java/com/synergyx/trading/model/PatternApply.java
  src/main/java/com/synergyx/trading/service/patternApplyService/PatternApplyCommandServiceImpl.java
  src/main/java/com/synergyx/trading/service/patternApplyService/PatternApplyQueryServiceImpl.java
Labels: ✨ feature
